# Generated by Django 4.2.23 on 2025-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, help_text='Впишите Вашу дату рождения в формате: дд.мм.гггг', max_length=10, null=True),
        ),
    ]
